apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 16.0.10
    helm:
      releaseName: minio
      values: |
        mode: standalone
        auth:
          rootUser: minioadmin
          rootPassword: minioadmin
        service:
          type: NodePort
        persistence:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true